# Change these first
owner: sadams0978 # Your GitHub organization or username, where this repository lives
repo: sam-upptime # The name of this repository

sites:
  - name: PEAKE Technology Partners
    url: https://peaketechnology.com/
    
  - name: PEAKE CW PSA
    url: https://na.myconnectwise.net
    icon: https://na.myconnectwise.net/v2025_1/favicon.ico
    
  - name: PEAKE Ninja
    url: https://us2.ninjarmm.com
    icon: https://us2.ninjarmm.com/img/favicon.png
    
  - name: PEAKE Voice
    url: https://voice.peaketechnology.com
    __dangerous__insecure: true

  - name: PEAKE O365
    url: https://login.microsoftonline.com/login.srf?whr=peaketechnology.com
    icon: https://res.cdn.office.net/officehub/images/content/images/favicon_m365-31d62b976c.ico
    
  - name: PASM
    check: "tcp-ping"
    url: pasm.peaketechnology.com
    icon: https://peaketechnology.com/wp-content/uploads/2022/11/cropped-PEAKE-Icon-32x32.png
    port: 81
    __dangerous__insecure: true
    
  - name: Rewst
    url: https:/app.rewst.io
    icon: https://app.rewst.io/favicon.ico

  - name: Client Portal (Testing)
    url: https:/cp.peaketechnology.com
    icon: https://cp.peaketechnology.com/favicon.ico

  - name: Client Portal (Production)
    url: https:/portal.peaketechnology.com
    icon: https://dd-files-main.imgix.net/peake/2023/3/D8qbdJ4gMEOCCsQss-HHmA/PEAKE_Logo.png
    
  - name: IT Glue
    url: https://peaketechnology.itglue.com
    icon: https://peaketechnology.itglue.com/favicon.ico
    
  - name: Cisco Meraki
    url: https://dashboard.meraki.com
    icon: https://dashboard.meraki.com/favicon.ico
    
  - name: Slack
    url: https://peaketechnology.slack.com
    icon: https://peaketechnology.slack.com/favicon.ico
  
  - name: Google DNS
    check: "tcp-ping"
    url: 8.8.8.8
    icon: https://www.google.com/favicon.ico
    port: 53
  
  - name: Cloudflare DNS
    check: "tcp-ping"
    url: 1.1.1.1
    icon: https://1.1.1.1/favicon.ico
    port: 53

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  
  #General Settings
  baseUrl: /sam-upptime
  theme: night
  favicon: https://peaketechnology.com/wp-content/uploads/2022/11/cropped-PEAKE-Icon-32x32.png

  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://peaketechnology.com/wp-content/uploads/2022/12/6389e642ac476c6c414d112c_peake_icon-1.png
  name: PEAKE Technology Partners
  introTitle: "**Welcome to our Uptime Page**"
  introMessage: Please Visit our GitHub Repo Above! 
  navbar:
    - title: Status
      href: /sam-upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
