# Change these first
owner: sadams0978 # Your GitHub organization or username, where this repository lives
repo: sam-upptime # The name of this repository

sites:
  - name: PEAKE Technology Partners
    url: https://peaketechnology.com/
    
  - name: PEAKE SSO
    url: https://sso.peaketechnology.com/adfs/ls/idpinitiatedsignon
    icon: https://peaketechnology.com/wp-content/uploads/2022/11/cropped-PEAKE-Icon-32x32.png
    
  - name: PEAKE CW Manage
    url: https://cw.peakesupport.com
    
  - name: PEAKE CW Automate
    url: https://lt.peakesupport.com/automate
    icon: https://lt.peakesupport.com/automate/favicon.ico
    
  - name: PEAKE CW Control
    url: https://help.peakesupport.com
    
  - name: PEAKE Voice
    url: https://voice.peaketechnology.com
    __dangerous__insecure: true
    
  - name: Vector Data Systems
    url: https://vectordatasystems.com
    
  - name: Vector DNS 1
    check: "tcp-ping"
    url: 199.96.108.108
    icon: https://vectordatasystems.com/wp-content/uploads/2021/02/cropped-fav_con_vector-270x270.png
    port: 53
    
  - name: PASM
    check: "tcp-ping"
    url: pasm.peakesupport.com
    icon: https://peaketechnology.com/wp-content/uploads/2022/11/cropped-PEAKE-Icon-32x32.png
    port: 81
    __dangerous__insecure: true
    
  - name: Rewst
    url: https:/app.rewst.io
    icon: https://app.rewst.io/favicon.ico
    
  - name: IT Glue
    url: https://peaketechnology.itglue.com
    icon: https://peaketechnology.itglue.com/favicon.ico
    
  - name: Cisco Meraki
    url: https:/dashboard.meraki.com
    icon: https://dashboard.meraki.com/favicon.ico
    
  - name: Slack
    url: https://peaketechnology.slack.com
    icon: https://peaketechnology.slack.com/favicon.ico


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  
  #General Settings
  baseUrl: /sam-upptime
  theme: night
  favicon: https://peaketechnology.com/wp-content/uploads/2022/11/cropped-PEAKE-Icon-32x32.png

  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://peaketechnology.com/wp-content/uploads/2022/12/6389e642ac476c6c414d112c_peake_icon-1.png
  name: PEAKE Technology Partners
  introTitle: "**Welcome to our Uptime Page**"
  introMessage: Please Visit our GitHub Repo Above! 
  navbar:
    - title: Status
      href: /sam-upptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
